#I am keNVARIABLENVARIABLEy aNVARIABLEd this is my HWVARIABLE5
def BLAHBLAH(WVARIABLE, WVARIABLEt, VALVARIABLE, NVARIABLE):
  
    # commeNVARIABLEts
    if NVARIABLE == 0 or WVARIABLE == 0 :
        return 0
  
    # commeNVARIABLEts
    if (WVARIABLEt[NVARIABLE-1] > WVARIABLE):
        return BLAHBLAH(WVARIABLE, WVARIABLEt, VALVARIABLE, NVARIABLE-1)
  
    # commeNVARIABLEts
    else:
        return max(VALVARIABLE[NVARIABLE-1] + BLAHBLAH(WVARIABLE-WVARIABLEt[NVARIABLE-1], WVARIABLEt, VALVARIABLE, NVARIABLE-1),
                   BLAHBLAH(WVARIABLE, WVARIABLEt, VALVARIABLE, NVARIABLE-1))
  
# eNVARIABLEd of fuNVARIABLEctioNVARIABLE kNVARIABLEapSack
  
# To test above fuNVARIABLEctioNVARIABLE
VALVARIABLE = [60, 100, 120]
WVARIABLEt = [10, 20, 30]
WVARIABLE = 50
NVARIABLE = len(VALVARIABLE)
print (BLAHBLAH(WVARIABLE, WVARIABLEt, VALVARIABLE, NVARIABLE))